const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //ADMIN
    FETCH_SEX_START: 'FETCH_SEX_START',
    FETCH_SEX_SUCCESS: 'FETCH_SEX_SUCCESS',
    FETCH_SEX_FAILED: 'FETCH_SEX_FAILED',

    FETCH_VIP_SUCCESS: 'FETCH_VIP_SUCCESS',
    FETCH_VIP_FAILED: 'FETCH_VIP_FAILED',

    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',

    CREAT_USER_SUCCESS: 'CREAT_USER_SUCCESS',
    CREAT_USER_FAILED: 'CREAT_USER_FAILED',

    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',

    FETCH_RECENTLY_USERS_SUCCESS: 'FETCH_RECENTLY_USERS_SUCCESS',
    FETCH_RECENTLY_USERS_FAILED: 'FETCH_RECENTLY_USERS_FAILED',

    CREAT_LIST_SOCIALS_SUCCESS: 'CREAT_LIST_SOCIALS_SUCCESS',
    CREAT_LIST_SOCIALS_FAILED: 'CREAT_LIST_SOCIALS_FAILED',

    FETCH_LIST_SOCIALS_SUCCESS: 'FETCH_LIST_SOCIALS_SUCCESS',
    FETCH_LIST_SOCIALS_FAILED: 'FETCH_LIST_SOCIALS_FAILED',

    DELETE_LIST_SOCIALS_SUCCESS: 'DELETE_LIST_SOCIALS_SUCCESS',
    DELETE_LIST_SOCIALS_FAILED: 'DELETE_LIST_SOCIALS_FAILED',

    EDIT_LIST_SOCIALS_SUCCESS: 'EDIT_LIST_SOCIALS_SUCCESS',
    EDIT_LIST_SOCIALS_FAILED: 'EDIT_LIST_SOCIALS_FAILED',

    CREAT_LIST_BANKS_SUCCESS: 'CREAT_LIST_BANKS_SUCCESS',
    CREAT_LIST_BANKS_FAILED: 'CREAT_LIST_BANKS_FAILED',

    FETCH_LIST_BANKS_SUCCESS: 'FETCH_LIST_BANKS_SUCCESS',
    FETCH_LIST_BANKS_FAILED: 'FETCH_LIST_BANKS_FAILED',

    DELETE_LIST_BANKS_SUCCESS: 'DELETE_LIST_BANKS_SUCCESS',
    DELETE_LIST_BANKS_FAILED: 'DELETE_LIST_BANKS_FAILED',

    EDIT_LIST_BANKS_SUCCESS: 'EDIT_LIST_BANKS_SUCCESS',
    EDIT_LIST_BANKS_FAILED: 'EDIT_LIST_BANKS_FAILED',

    FETCH_SOCIALS_SUCCESS: 'FETCH_SOCIALS_SUCCESS',
    FETCH_SOCIALS_FAILED: 'FETCH_SOCIALS_FAILED',

    DELETE_SOCIALS_SUCCESS: 'DELETE_SOCIALS_SUCCESS',
    DELETE_SOCIALS_FAILED: 'DELETE_SOCIALS_FAILED',

    FETCH_BANKS_SUCCESS: 'FETCH_BANKS_SUCCESS',
    FETCH_BANKS_FAILED: 'FETCH_BANKS_FAILED',

    DELETE_BANKS_SUCCESS: 'DELETE_BANKS_SUCCESS',
    DELETE_BANKS_FAILED: 'DELETE_BANKS_FAILED',

    FETCH_EMAILS_SUCCESS: 'FETCH_EMAILS_SUCCESS',
    FETCH_EMAILS_FAILED: 'FETCH_EMAILS_FAILED',

    DELETE_EMAILS_SUCCESS: 'DELETE_EMAILS_SUCCESS',
    DELETE_EMAILS_FAILED: 'DELETE_EMAILS_FAILED',

    FETCH_PHONES_SUCCESS: 'FETCH_PHONES_SUCCESS',
    FETCH_PHONES_FAILED: 'FETCH_PHONES_FAILED',

    DELETE_PHONES_SUCCESS: 'DELETE_PHONES_SUCCESS',
    DELETE_PHONES_FAILED: 'DELETE_PHONES_FAILED',

    FETCH_LOCATIONS_SUCCESS: 'FETCH_LOCATIONS_SUCCESS',
    FETCH_LOCATIONS_FAILED: 'FETCH_LOCATIONS_FAILED',

    DELETE_LOCATIONS_SUCCESS: 'DELETE_LOCATIONS_SUCCESS',
    DELETE_LOCATIONS_FAILED: 'DELETE_LOCATIONS_FAILED',

    FETCH_CUSTOMS_SUCCESS: 'FETCH_CUSTOMS_SUCCESS',
    FETCH_CUSTOMS_FAILED: 'FETCH_CUSTOMS_FAILED',

    DELETE_CUSTOMS_SUCCESS: 'DELETE_CUSTOMS_SUCCESS',
    DELETE_CUSTOMS_FAILED: 'DELETE_CUSTOMS_FAILED',

    // USER MANAGE

    UPDATE_USER_INFO_LOCAL_SUCCESS: 'UPDATE_USER_INFO_LOCAL_SUCCESS'

})

export default actionTypes;